times = ('Botafogo', 'Palmeiras', 'Fluminense', 'Atlético-MG', 'Cruzeiro','Flamengo','Athletico-PR', 'São Paulo','Santos' ,'Grêmio', 'Fortaleza', 'Bragantino', 'Bahia', 'Cuiabá','Internacional','Goiás', 'Vasco', 'Corinthians','América-MG', 'Coritiba')
print('-+-'*20)
print(f'Tabela do Brasileirão: {times}')
print('-+-'*20)
print(f'Esses são os 5 primeiros colocados: {times[0:5]}')
print('-+-'*20)
print(f'Esses são os 4 ultimos: {times[-4:]}')
print('-+-'*20)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-+-'*20)
print(f'O Vasco está em {times.index("Vasco")+1}° colocação')